name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    label: 'chore'
exclude-labels:
  - 'skip-changelog'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Get it
  Install it with pip
  ```bash
  pip install hdate==$RESOLVED_VERSION
  ```
  See it on pypi: [https://pypi.org/project/hdate](https://pypi.org/project/hdate/$RESOLVED_VERSION/)

  ## Changes

  $CHANGES